### ISSUE TITLE
Errenous HTTP 500 (I think)

### ISSUE THREAD

**Issue by apokalyptik** [bjork/phpcompatapi#4]
with

``` php
<?

echo "foo";
```

api/v1/test/ returns (sort of correctly) `{"error":"Unable to parse the file."}` but with an http 500 causing a console log event

**Comment by bjork** [comment]
Can't reproduce this – not sure if it's related to the usage of short tags in your example or what. But on a general level I think it is totally fine. This specific error message only happens if PHP CompatInfo returns or throws an exception while trying to analyze the file. To me, the semantics of HTTP 500 apply here – the API should try to be as RESTful as it can be.
